name: "🐛 Bug Report"
description: "Report a reproducible bug or regression."
title: "[BUG]: "
labels: [ "bug" ]
body:
  - type: markdown
    attributes:
      value: |
        Please provide detailed information about the bug you're experiencing.

  - type: textarea
    id: current-behavior
    attributes:
      label: Current Behavior
      description: Describe how the issue manifests.
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: Describe what the desired behavior would be.
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Please provide detailed steps to reproduce the issue.
      placeholder: |
        1. 
        2. 
        3.
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: Version set in package.json
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      options:
        - Windows
        - macOS
        - Linux
    validations:
      required: true

  - type: input
    id: os-version
    attributes:
      label: OS Version
    validations:
      required: true

  - type: input
    id: node-version
    attributes:
      label: Node.js Version
      description: Output of running `node -v`
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: |
        - 
        - 
        -
    validations:
      required: false
