name: '✨ Feature request'
description: 'Suggest an amazing new idea for this project'
title: '[FEATURE]: '
labels: ['enhancement']
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature!

  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: Is your feature request related to a problem? Please describe.
      placeholder: A clear and concise description of what the problem is. Ex. I have an issue when [...]
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: A clear and concise description of what you want to happen. Add any considered drawbacks.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe alternatives you've considered
      placeholder: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: true

  - type: dropdown
    id: contribution
    attributes:
      label: Are you willing to resolve this issue by submitting a Pull Request?
      description: Remember that first-time contributors are welcome! 🙌
      options:
        - "Yes, I have the time, and I know how to start."
        - "Yes, I have the time, but I don't know how to start. I would need guidance."
        - "No, I don't have the time, although I believe I could do it if I had the time..."
        - "No, I don't have the time and I wouldn't even know how to start."
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        👋 Have a great day and thank you for the feature request!