name: '🔒 Security Vulnerability Report'
description: 'Report a security vulnerability in this project'
labels: ['security', 'confidential']
body:
  - type: markdown
    attributes:
      value: |
        # Security Vulnerability Report
        
        Thank you for taking the time to report a security vulnerability. We take all security reports seriously and will respond as quickly as possible.
        
        ⚠️ **IMPORTANT**: If you believe you've found a critical security vulnerability, please do NOT create a public issue. Instead, please contact maintainers directly.
        
        This template is for reporting less critical security concerns that don't pose an immediate risk to users.

  - type: dropdown
    id: vulnerability-type
    attributes:
      label: Type of Security Vulnerability
      description: Select the category that best describes the security issue
      options:
        - Injection Vulnerability
        - Authentication Issue
        - Data Exposure
        - Access Control
        - Security Misconfiguration
        - Dependency Vulnerability
        - Cross-site Scripting (XSS)
        - Other (specify in description)
    validations:
      required: true

  - type: textarea
    id: vulnerability-description
    attributes:
      label: Vulnerability Description
      description: Provide a clear and detailed description of the security vulnerability
      placeholder: |
        Please include:
        - What components are affected
        - How the vulnerability could be exploited
        - Potential impact on the system/users
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Provide detailed steps to reproduce the vulnerability
      placeholder: |
        1. Configure the system with...
        2. Send a request to...
        3. Modify the payload to...
        4. Observe that...
    validations:
      required: true

  - type: textarea
    id: proof-of-concept
    attributes:
      label: Proof of Concept
      description: If possible, provide a proof of concept or example that demonstrates the vulnerability (but nothing that could cause harm)
      placeholder: |
        ```
        // Example code or configuration that demonstrates the vulnerability
        // DO NOT include exploits or harmful code
        ```

  - type: dropdown
    id: severity
    attributes:
      label: Estimated Severity
      description: Based on your assessment, how severe is this vulnerability?
      options:
        - Critical (Immediate exploitation risk, severe impact)
        - High (Significant risk or impact)
        - Medium (Moderate risk or impact)
        - Low (Minor risk or impact)
        - Info (General security concern)
    validations:
      required: true

  - type: textarea
    id: mitigation
    attributes:
      label: Suggested Mitigation
      description: If you have ideas for how this vulnerability could be fixed, please share them
      placeholder: Consider implementing input validation, updating dependencies, etc.

  - type: input
    id: affected-versions
    attributes:
      label: Affected Versions
      description: What versions of the project are affected by this vulnerability?
      placeholder: e.g., 1.2.0 through 1.3.5
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other relevant information about the vulnerability
      placeholder: Include references to related CVEs, security advisories, or other relevant documentation

  - type: checkboxes
    id: terms
    attributes:
      label: Security Report Agreement
      description: By submitting this report, you agree to the following
      options:
        - label: I have not publicly disclosed this security issue to exploit before
          required: true
        - label: I have not exploited this vulnerability beyond necessary testing and reporting
          required: true
        - label: The information provided is accurate to the best of my knowledge
          required: true

  - type: markdown
    attributes:
      value: |
        Thank you for helping keep our project secure! We will review your report and respond as soon as possible.
        
        For critical vulnerabilities, remember to contact our security team directly instead of using this template.