export default {
    home: '/',
    about: '/about',
    signIn: '/sign-in',
    signUp: '/sign-up',
    profile: '/profile',
    gameTest: '/game-test',
    viewCharacter: '/lobby-room/:lobbyId/view-character',
    lobbyRoom: '/lobby-room/:lobbyId',
    gameRoom: '/lobby-room/:lobbyId/game-room/:gameId',
    createCombatRoom: '/lobby-room/:lobbyId/create-combat',
    createCharacter: '/lobby-room/:lobbyId/create-character',
    wiki: '/game-wiki',
    wikiWithDLC: '/game-wiki/:dlc',
}
